Basecom\Bundle\ShopwareConnectorBundle\Entity\Attribute:
    type: entity
    table: pim_catalog_attribute
    repositoryClass: Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\AttributeRepository
    fields:
        sid:
            type: integer
            nullable: true
            unique: true