Basecom\Bundle\ShopwareConnectorBundle\Entity\Category:
    type: entity
    table: pim_catalog_category
    repositoryClass: Akeneo\Bundle\ClassificationBundle\Doctrine\ORM\Repository\CategoryRepository
    fields:
        sid:
            type: integer
            nullable: true
            unique: true