Basecom\Bundle\ShopwareConnectorBundle\Entity\Family:
    type: entity
    table: pim_catalog_family
    repositoryClass: Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\FamilyRepository
    fields:
        swId:
            type: integer
            nullable: true
            unique: true