Basecom\Bundle\ShopwareConnectorBundle\Entity\FileInfo:
    type: entity
    table: akeneo_file_storage_file_info
    repositoryClass: Basecom\Bundle\ShopwareConnectorBundle\Entity\Repository\FileInfoRepository
    fields:
        swMediaId:
            type: integer
            nullable: true
            unique: true