connector:
    name: Shopware Connector
    jobs:
        shopware_products_export:
            title: Shopware product export
            type: export
            steps:
                export_products:
                    title:          Shopware product export
                    services:
                        reader:     basecom_shopware_connector.reader.shopware_product_export
                        processor:  basecom_shopware_connector.processor.shopware_product
                        writer:     basecom_shopware_connector.writer.shopware_product
#                export_product_images:
#                    title:          Shopware product image export
#                    class:          "%basecom_shopware_connector.step.product_image.class%"
#                    services:
#                        handler:    basecom_shopware_connector.handler.product_image
#        shopware_product_images_export:
#            title: Shopware product images export
#            type: export
#            steps:
#                export_products:
#                    title:          Shopware product images export
#                    services:
#                        reader:     basecom_shopware_connector.reader.shopware_product_image
#                        processor:  basecom_shopware_connector.processor.shopware_product_image
#                        writer:     basecom_shopware_connector.writer.shopware_product_image
#        shopware_import:
#            title: Shopware import
#            type: import
#            steps:
#                import_categories:
#                    title:          Shopware category import
#                    services:
#                        reader:     basecom_shopware_connector.reader.shopware_category
#                        processor:  pim_connector.processor.denormalization.category.flat
#                        writer:     pim_connector.writer.doctrine.category
#                    parameters:
#                        batchSize: 1
#                import_attribute_groups:
#                    title:          Shopware attribute group import
#                    services:
#                        reader:     basecom_shopware_connector.reader.shopware_attribute_group
#                        processor:  pim_base_connector.processor.attribute_group
#                        writer:     pim_base_connector.writer.doctrine
#                import_attributes:
#                    title:          Shopware attribute import
#                    services:
#                        reader:     basecom_shopware_connector.reader.shopware_attribute
#                        processor:  pim_connector.processor.denormalization.attribute.flat
#                        writer:     pim_connector.writer.doctrine.attribute
#                import_attribute_options:
#                    title:          Shopware attribute options import
#                    services:
#                        reader:     basecom_shopware_connector.reader.shopware_attribute_option
#                        processor:  pim_connector.processor.denormalization.attribute_option.flat
#                        writer:     pim_connector.writer.doctrine.attribute_option
#                import_families:
#                    title:          Shopware family import
#                    services:
#                        reader:     basecom_shopware_connector.reader.shopware_family
#                        processor:  pim_connector.processor.denormalization.family.flat
#                        writer:     pim_connector.writer.doctrine.family
#
#        shopware_products_import:
#            title: Shopware product import
#            type: import
#            steps:
#                import_products:
#                    title:          Shopware product import
#                    services:
#                        reader:     basecom_shopware_connector.reader.shopware_product
#                        processor:  pim_connector.processor.denormalization.product.flat
#                        writer:     pim_connector.writer.doctrine.product
#                import_association_types:
#                    title:          Shopware association types import
#                    class:          "%basecom_shopware_connector.step.association_type.class%"
#                    services:
#                        handler:    basecom_shopware_connector.handler.association_type
#                import_associations:
#                    title:          Shopware associations import
#                    services:
#                        reader:     basecom_shopware_connector.reader.shopware_association
#                        processor:  pim_connector.processor.denormalization.product_association.flat
#                        writer:     pim_connector.writer.doctrine.product_association
#                import_product_images:
#                    title:          Shopware product image import
#                    class:          "%basecom_shopware_connector.step.product_image.class%"
#                    services:
#                        handler:    basecom_shopware_connector.handler.product_image

        shopware_export:
            title: Shopware export
            type: export
            steps:
                export_categories:
                    title:          Shopware category export
                    services:
                        reader:     basecom_shopware_connector.reader.shopware_category_export
                        processor:  basecom_shopware_connector.processor.shopware_category
                        writer:     basecom_shopware_connector.writer.shopware_category
                export_families:
                    title:          Shopware family export
                    services:
                        reader:     basecom_shopware_connector.reader.shopware_family_export
                        processor:  basecom_shopware_connector.processor.shopware_family
                        writer:     basecom_shopware_connector.writer.shopware_family