connector:
    name: Shopware Connector
    jobs:
        shopware_products_export:
            title: Shopware product export
            type: export
            steps:
                export_products:
                    title:          Shopware product export
                    services:
                        reader:     basecom_shopware_connector.reader.shopware_product_export
                        processor:  basecom_shopware_connector.processor.shopware_product
                        writer:     basecom_shopware_connector.writer.shopware_product
        shopware_export:
            title: Shopware export
            type: export
            steps:
                export_categories:
                    title:          Shopware category export
                    services:
                        reader:     basecom_shopware_connector.reader.shopware_category_export
                        processor:  basecom_shopware_connector.processor.shopware_category
                        writer:     basecom_shopware_connector.writer.shopware_category
                export_families:
                    title:          Shopware family export
                    services:
                        reader:     basecom_shopware_connector.reader.shopware_family_export
                        processor:  basecom_shopware_connector.processor.shopware_family
                        writer:     basecom_shopware_connector.writer.shopware_family