connector:
    name: Shopware Connector
    jobs:
        shopware_products_export:
            title: basecom_shopware_connector.jobs.shopware_products_export.title
            type: export
            steps:
                shopware.clean.products:
                    title:          basecom_shopware_connector.jobs.shopware_products_export.clean_products.title
                export_products:
                    title:          basecom_shopware_connector.jobs.shopware_products_export.export_products.title
                    services:
                        reader:     basecom_shopware_connector.reader.shopware_product_export
                        processor:  basecom_shopware_connector.processor.shopware_product
                        writer:     basecom_shopware_connector.writer.shopware_product
        shopware_export:
            title: basecom_shopware_connector.jobs.shopware_export.title
            type: export
            steps:
                export_categories:
                    title:          basecom_shopware_connector.jobs.shopware_export.export_categories.title
                    services:
                        reader:     basecom_shopware_connector.reader.shopware_category_export
                        processor:  basecom_shopware_connector.processor.shopware_category
                        writer:     basecom_shopware_connector.writer.shopware_category
                export_families:
                    title:          basecom_shopware_connector.jobs.shopware_export.export_categories.title
                    services:
                        reader:     basecom_shopware_connector.reader.shopware_family_export
                        processor:  basecom_shopware_connector.processor.shopware_family
                        writer:     basecom_shopware_connector.writer.shopware_family
        shopware_attribute_setup:
            title: basecom_shopware_connector.jobs.shopware_attribute_setup.title
            type: import
            steps:
                import:
                    title:          basecom_shopware_connector.jobs.shopware_attribute_setup.import.title
                    class:          "%basecom_shopware_connector.step.setup_attributes.class%"
                    services:
                        handler:    basecom_shopware_connector.handler.attribute_setup