parameters:
    pim_catalog.entity.category.class:              Basecom\Bundle\ShopwareConnectorBundle\Entity\Category
    pim_catalog.entity.family.class:                Basecom\Bundle\ShopwareConnectorBundle\Entity\Family
    pim_catalog.entity.product.class:               Basecom\Bundle\ShopwareConnectorBundle\Entity\Product
    akeneo_file_storage.model.file_info.class:      Basecom\Bundle\ShopwareConnectorBundle\Entity\FileInfo
    pim_catalog.repository.product.class:           Basecom\Bundle\ShopwareConnectorBundle\Entity\Repository\ProductRepository
    akeneo_file_storage.repository.file_info.class: Basecom\Bundle\ShopwareConnectorBundle\Entity\Repository\FileInfoRepository