parameters:
    pim_catalog.entity.category.class:          Basecom\Bundle\ShopwareConnectorBundle\Entity\Category
    pim_catalog.entity.family.class:            Basecom\Bundle\ShopwareConnectorBundle\Entity\Family