parameters:
    basecom_shopware_connector.job.job_parameters.default_values_provider.shopware_export.class:        Basecom\Bundle\ShopwareConnectorBundle\Job\JobParameters\DefaultValuesProvider\ShopwareExport
    basecom_shopware_connector.job.job_parameters.constraint_collection_provider.shopware_export.class: Basecom\Bundle\ShopwareConnectorBundle\Job\JobParameters\ConstraintCollectionProvider\ShopwareExport
    basecom_shopware_connector.job.job_parameters.form_configuration_provider.shopware_export.class: Basecom\Bundle\ShopwareConnectorBundle\Job\JobParameters\FormConfigurationProvider\ShopwareExport
    basecom_shopware_connector.job.job_parameters.constraint_collection_provider.attribute_setup.class: Basecom\Bundle\ShopwareConnectorBundle\Job\JobParameters\AttributeSetup
    basecom_shopware_connector.job.job_parameters.constraint_collection_provider.product_export.class: Basecom\Bundle\ShopwareConnectorBundle\Job\JobParameters\ProductExport

services:
    basecom_shopware_connector.job.job_parameters.default_values_provider.shopware_export:
        class: '%basecom_shopware_connector.job.job_parameters.default_values_provider.shopware_export.class%'
        arguments:
            -
                - 'shopware_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    basecom_shopware_connector.job.job_parameters.constraint_collection_provider.shopware_export:
        class: '%basecom_shopware_connector.job.job_parameters.constraint_collection_provider.shopware_export.class%'
        arguments:
            -
                - 'shopware_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    basecom_shopware_connector.job.job_parameters.form_configuration_provider.shopware_export:
        class: '%basecom_shopware_connector.job.job_parameters.form_configuration_provider.shopware_export.class%'
        arguments:
            -
                - 'shopware_export'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.category'
        tags:
            - { name: pim_import_export.job_parameters.form_configuration_provider }

    basecom_shopware_connector.job.job_parameters.constraint_collection_provider.attribute_setup:
        class: '%basecom_shopware_connector.job.job_parameters.constraint_collection_provider.attribute_setup.class%'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
            - { name: pim_import_export.job_parameters.form_configuration_provider }

    basecom_shopware_connector.job.job_parameters.constraint_collection_provider.product_export:
        class: '%basecom_shopware_connector.job.job_parameters.constraint_collection_provider.product_export.class%'
        arguments:
            - '@pim_user.context.user'
            - '@pim_catalog.repository.category'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.currency'
            - '@pim_catalog.repository.association_type'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
            - { name: pim_import_export.job_parameters.form_configuration_provider }