job_templates:
    shopware_categories_export:
        templates:
            edit: "BasecomShopwareConnectorBundle:BasecomExportProfile:edit.html.twig"

    shopware_families_export:
        templates:
            edit: "BasecomShopwareConnectorBundle:BasecomExportProfile:edit.html.twig"

    shopware_product_export:
        templates:
            edit: "BasecomShopwareConnectorBundle:BasecomExportProfile:edit.html.twig"