parameters:
    basecom_shopware_connector.processor.simple_item.class:         Basecom\Bundle\ShopwareConnectorBundle\Processor\SimpleItemProcessor
    basecom_shopware_connector.processor.shopware_product.class:        Basecom\Bundle\ShopwareConnectorBundle\Processor\ShopwareProductProcessor
services:
    basecom_shopware_connector.processor.simple_item:
        class: '%basecom_shopware_connector.processor.simple_item.class%'

    basecom_shopware_connector.processor.shopware_product:
        class: '%basecom_shopware_connector.processor.shopware_product.class%'
        arguments:
            - '@basecom_shopware_connector.serializer.shopware_product'
