parameters:
    basecom_shopware_connector.step.product_image.class:        Basecom\Bundle\ShopwareConnectorBundle\Step\ProductImageStep
    basecom_shopware_connector.handler.product_image.class:     Basecom\Bundle\ShopwareConnectorBundle\Handler\ProductImageHandler
    basecom_shopware_connector.step.association_type.class:     Basecom\Bundle\ShopwareConnectorBundle\Step\AssociationTypeStep
    basecom_shopware_connector.handler.association_type.class:  Basecom\Bundle\ShopwareConnectorBundle\Handler\AssociationTypeHandler
services:
    basecom_shopware_connector.handler.product_image:
        class: %basecom_shopware_connector.handler.product_image.class%
        arguments:
            - '@pim_catalog.repository.attribute'
    basecom_shopware_connector.handler.association_type:
        class: %basecom_shopware_connector.handler.association_type.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@pim_catalog.repository.association_type"